reject = 10;         # Reject obvious spam
add_header = null;   # Add spam headers, deliver
rewrite_subject = 6; # Add spam note to subject
greylist = null;     # Temporarily delay suspicious messages

subject = "[SPAM] %s"; # Custom rewrite prefix
