services:
  unbound:
    container_name: unbound
    image: klutchell/unbound:latest
    networks:
      - dns
    restart: unless-stopped
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf.d/unbound.conf:ro
    labels:
      docs.description: "Upstream DNS for pihole, also used by rspamd"

networks:
  dns:
    external: true