protocols = imap

ssl = no
auth_mechanisms = plain login
auth_allow_cleartext = yes
auth_username_format = archive

mail_driver = Maildir
mail_path = /srv/vmail/%{user}/Maildir
mail_index_path = /var/indexes/%{user}
mailbox_list_layout = fs
mail_prefetch_count = 0
lda_mailbox_autocreate = yes

log_path = /dev/stdout
info_log_path = /dev/stdout
