services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../../data/dockhand:/app/data
    labels:
      docs.description: "Docker management platform for logs and container control"

      traefik.enable: "true"
      traefik.docker.network: proxy

      traefik.http.routers.dockhand.rule: Host(`dockhand.rasputin.pi`)
      traefik.http.routers.dockhand.entrypoints: websecure
      traefik.http.routers.dockhand.tls: "true"

      traefik.http.services.dockhand.loadbalancer.server.port: 3000

      homepage.group: Tooling
      homepage.name: Dockhand
      homepage.icon: dockhand
      homepage.href: https://dockhand.rasputin.pi
      homepage.description: Docker Management

      homepage.widget.type: dockhand
      homepage.widget.url: http://dockhand:3000
      homepage.widget.fields: '["running","pending_updates"]'
      homepage.widget.highlight.pending_updates.numeric[0].level: danger
      homepage.widget.highlight.pending_updates.numeric[0].when: gte
      homepage.widget.highlight.pending_updates.numeric[0].value: 1

networks:
  proxy:
    external: true
