services:
  wireguard-client:
    image: linuxserver/wireguard:latest
    container_name: wireguard-client
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ../../../data/wireguard-client:/config
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped
    labels:
      docs.description: "Temporary WireGuard client for hole-punching through NAT"

      homepage.group: Network
      homepage.name: WireGuard Client
      homepage.icon: wireguard
      homepage.description: VPN